### ISSUE TITLE
"Your Boards"  -- consider showing a message like "you don't have any boards yet -- want to create a new one?" message if a user doesn't have any boards and clicks the dropdown on the sidebar

### ISSUE THREAD

**Issue by stuba2** [KG00D/Jello#176]
"Your Boards"  -- consider showing a message like "you don't have any boards yet -- want to create a new one?" message if a user doesn't have any boards and clicks the dropdown on the sidebar

**Comment by MHung31** [comment]
added "No boards have been added yet" in the side panel if no boards

**Comment by MHung31** [comment]
Added feature
