### ISSUE TITLE
For cards, if a user edits the card title and clicks out of the div, users might expect their udpate to save.  This is because boards have this functionality so we it may be beneficial to have some consistency between how these two featuers update

### ISSUE THREAD

**Issue by stuba2** [KG00D/Jello#177]
For cards, if a user edits the card title and clicks out of the div, users might expect their udpate to save.  This is because boards have this functionality so we it may be beneficial to have some consistency between how these two featuers update

**Comment by MHung31** [comment]
Updated onblur to update card title
