### ISSUE TITLE
When the card/comments modal is open consider having functionallity where a user can "close" out of the modal by clicking above or below the modal.  Currently only clicking the sides outside of the modal close the modal

### ISSUE THREAD

**Issue by stuba2** [KG00D/Jello#178]
When the card/comments modal is open consider having functionallity where a user can "close" out of the modal by clicking above or below the modal.  Currently only clicking the sides outside of the modal close the modal

**Comment by MHung31** [comment]
This isn't worth fixing unless we refactor editcardmodal since there's a large modal element in the way preventing clicking above or below
