### ISSUE TITLE
Docs - To be added

### ISSUE THREAD

**Issue by MHung31** [KG00D/Jello#22]
**Routes**
User Routes
/api/users/
Query for all users and returns them in a list of user
dictionaries.
/api/users/<int:id>
Query for a user by id and returns that user in a dictionary.

**Auth Routes**
/api/auth/
Authenticates a user.
/api/auth/login
Logs in a user.
/api/auth/logout
Logs a user out.
/api/auth/signup
Creates a new user and logs them in.
/api/auth/unauthorized
Returns unauthorized JSON when flask-login authentication fails.

**Comment by stuba2** [comment]
I think we still need the Auth routes
